### ISSUE TITLE
Sponsorship ended, anything I can do?

### ISSUE THREAD

**Issue by vorburger** [indeedeng/FOSS-Contributor-Fund#16]
Thank You very much for having sponsored me on GitHub for the past year! It means the world to me.

I just noticed that your sponsorship recently ended, and was basically just curious for some feedback:

Did you perhaps meanwhile simply stop using... probably [MariaDB4j](https://github.com/vorburger/MariaDB4j/)?

Is there anything I can do 😃 better? 

@DuaneOBrien

**Comment by DuaneOBrien** [comment]
Hi @vorburger, it's great to hear from you!

We have a rolling process that ages out our GitHub Sponsorships, so that we know we're regularly evaluating our usage of the projects, the activity of folks we sponsor, and the available funding. We have a new set of sponsorships starting up this week, and you're in the list along with a lot of folks.

I don't have any requests for the time being. Thanks for everything you do for open source!

**Comment by vorburger** [comment]
Thanks!!
